export const pokemons = [
  "ampharos",
  "arcanine",
  "baxcalibur",
  "bulbasaur",
  "charmander",
  "cyclizar",
  "dondozo",
  "eevee",
  "entei",
  "espathra",
  "flaaffy",
  "fuecoco",
  "growlithe",
  "hawlucha",
  "koraidon",
  "lucario",
  "mimikyu",
  "miraidon",
  "murkrow",
  "ninetales",
  "pawmot",
  "pelipper",
  "pikachu",
  "quaquaval",
  "quaxly",
  "ravavroom",
  "smoliv",
  "spidops",
  "sprigatito",
  "squirtle",
  "tinkaton",
].map((pokemon, index) => {
  return { id: index + 1, name: pokemon, clicked: false };
});
